version: '3.8'

services:
  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: vegaburguer
      MYSQL_USER: practica
      MYSQL_PASSWORD: 1234
    #volumes:
     #- ./mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"